apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
        - name: server
          image: gcr.io/poised-octane-241023/restaurant-app
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"


